# https://qiita.com/fumihiko-hidaka/items/eb4031d72ad0be7a4ecd
# 最新3バージョン残し、それより古いバージョンを削除する
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
      - -c
      - gcloud app versions list --service=default | grep default | sort -rk 4,4 | awk '{print $2}' | tail -n +4 | xargs -I {} gcloud app versions delete {}

options:
  logging: CLOUD_LOGGING_ONLY
